Repository uwblueprint/website-bp, pull requests merged in 2022-10, with the labels that each got.

#82 Create SelectInput, TextAreaInput, and TextInput form components
  components/apply/AppForm.tsx
  components/common/SelectInput.tsx
  components/common/TextAreaInput.tsx
  components/common/TextInput.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: ready for review

#83 Create short answers questions section
  components/apply/AppForm.tsx
  components/apply/ShortAnswers.tsx
Labels: ready for review

#86 Basic Information Section
  components/apply/AppForm.tsx
  components/apply/BasicInfo.tsx
  components/apply/ShortAnswers.tsx
Labels: ready for review

#84 Application Position Preference Section
  components/apply/AppForm.tsx
  components/apply/PositionPreference.tsx
Labels: wip

#85 Implement Self ID Form for Application Form
  components/apply/AppForm.tsx
  components/apply/SelfIdentification.tsx
Labels: ready to merge ✅

#89 Add application header text section
  components/apply/AppForm.tsx
  components/apply/InfoText.tsx
Labels: ready to merge ✅

#88 Implement Role Specific Questions Component
  components/apply/AppForm.tsx
  components/apply/RoleSpecificQuestions.tsx
  constants/role-specific-questions.json
Labels: ready to merge ✅

#94 Add read only to Basic Info application section
  components/apply/AppForm.tsx
  components/apply/BasicInfo.tsx
Labels: ready for review
